"""user

Revision ID: db40388c13b0
Revises: 
Create Date: 2026-05-30 15:37:47.718870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db40388c13b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pump_runs')
    with op.batch_alter_table('sms_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_direction_status'))
        batch_op.drop_index(batch_op.f('idx_phone_created'))
        batch_op.drop_index(batch_op.f('idx_related_sms'))
        batch_op.drop_index(batch_op.f('ix_sms_log_phone'))

    op.drop_table('sms_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone'))

    op.drop_table('user')
    op.drop_table('pumps')
    with op.batch_alter_table('gpio_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_device_enabled'))

    op.drop_table('gpio_config')
    with op.batch_alter_table('phase_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phase_log_timestamp'))

    op.drop_table('phase_log')
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sender_status'))
        batch_op.drop_index(batch_op.f('idx_status_priority'))
        batch_op.drop_index(batch_op.f('ix_command_sender_phone'))

    op.drop_table('command')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ctype', sa.VARCHAR(length=10), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=6), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('duration_sec', sa.FLOAT(), nullable=True),
    sa.Column('remaining_sec', sa.FLOAT(), nullable=True),
    sa.Column('in_progress', sa.BOOLEAN(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('sms_id', sa.INTEGER(), nullable=True),
    sa.Column('sender_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('terminated_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sms_id'], ['sms_log.id'], ),
    sa.ForeignKeyConstraint(['terminated_by'], ['command.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_sender_phone'), ['sender_phone'], unique=False)
        batch_op.create_index(batch_op.f('idx_status_priority'), ['status', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_sender_status'), ['sender_phone', 'status'], unique=False)

    op.create_table('phase_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('green_led', sa.BOOLEAN(), nullable=False),
    sa.Column('yellow_led', sa.BOOLEAN(), nullable=False),
    sa.Column('red_led', sa.BOOLEAN(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phase_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phase_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('gpio_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gpio_pin', sa.INTEGER(), nullable=False),
    sa.Column('gpio_key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('device_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('gpio_type', sa.VARCHAR(length=6), nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gpio_key'),
    sa.UniqueConstraint('gpio_pin'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('gpio_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_device_enabled'), ['device_type', 'enabled'], unique=False)

    op.create_table('pumps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('desc', sa.VARCHAR(length=100), nullable=True),
    sa.Column('gpio_config_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['gpio_config_id'], ['gpio_config.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=True),
    sa.Column('is_owner', sa.BOOLEAN(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.Column('date_joined', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=1)

    op.create_table('sms_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('direction', sa.VARCHAR(length=8), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('channel', sa.VARCHAR(length=20), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('related_sms_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=12), nullable=False),
    sa.Column('is_authorized', sa.BOOLEAN(), nullable=True),
    sa.Column('is_processed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.Column('error_info', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['related_sms_id'], ['sms_log.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_log_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('idx_related_sms'), ['related_sms_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_phone_created'), ['phone', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_direction_status'), ['direction', 'status'], unique=False)

    op.create_table('pump_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pump_id', sa.INTEGER(), nullable=False),
    sa.Column('on_command_id', sa.INTEGER(), nullable=False),
    sa.Column('on_time', sa.DATETIME(), nullable=False),
    sa.Column('off_command_id', sa.INTEGER(), nullable=True),
    sa.Column('off_time', sa.DATETIME(), nullable=True),
    sa.Column('duration_sec', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['off_command_id'], ['command.id'], ),
    sa.ForeignKeyConstraint(['on_command_id'], ['command.id'], ),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
